//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersManagement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecureCoreOrderEntities : DbContext
    {
        public SecureCoreOrderEntities()
            : base("name=SecureCoreOrderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agencies> Agencies { get; set; }
        public virtual DbSet<Alumnes> Alumnes { get; set; }
        public virtual DbSet<Factories> Factories { get; set; }
        public virtual DbSet<OperationalAreas> OperationalAreas { get; set; }
        public virtual DbSet<OrderInfo> OrderInfo { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrdersDetail> OrdersDetail { get; set; }
        public virtual DbSet<Planets> Planets { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<References> References { get; set; }
    }
}
